import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import SideBarComponent from "@/components/MyUi/SideBarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-Merriweather",
  weight: "300",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased bg-gray-200`}
      >
        <main className="flex gap-[4%]">
          <SideBarComponent />
          {children}
        </main>
      </body>
    </html>
  );
}
